@baseUrl = http://localhost
@port = 8080
@host = {{baseUrl}}:{{port}}

# Create User
POST {{host}}/user HTTP/1.1
Content-Type: application/json

{
  "username": "nimbo",
  "email": "matlopes1999@gmail.com",
  "password": "add-your-password"
}
